apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 500Mi  # Modify the storage size as per your requirements
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Modify the storage class name as per your requirements
  hostPath:
    path: /data  # Modify the host path to match your storage location
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi  # Modify the storage size as per your requirements, should match the PV size
  storageClassName: standard  # Modify the storage class name as per your requirements
